import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="nl">
      <body>
        <nav
          aria-label="Skip links and accessibility options"
          className="sr-only focus-within:not-sr-only absolute top-0 left-0 w-full bg-gray-100 dark:bg-gray-800 p-2"
        >
          <ul className="flex gap-4 p-2">
            <li>
              <a
                href="#main"
                className="focus:outline-none focus:ring-2 focus:ring-blue-500 p-2"
              >
                Skip to main content
              </a>
            </li>
          </ul>
        </nav>

        <div className="flex flex-col min-h-screen">
          <header className="bg-govBlue-800 text-white p-4 shadow-md">
            <div className="container  mx-auto flex justify-between items-center">
              <h1 className="text-lg font-bold">Mijn Formulier</h1>
              <nav className="space-x-4">
                <a href="#" className="hover:underline">
                  Over
                </a>
                <a href="#" className="hover:underline">
                  Contact
                </a>
              </nav>
            </div>
          </header>

          <div className="container  mx-auto flex flex-1 mt-8 dark:bg-gray-900">
            {children}
          </div>

          <footer className="bg-white dark:bg-gray-900 p-4 border-t mt-8 border-gray-300">
            <div className="container  mx-auto flex justify-start">
              <p className="font-bold text-black dark:text-white">
                Vlaamse Overheid Formulier
              </p>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
